### ISSUE TITLE
Error when downloading raster data

### ISSUE THREAD

**Issue by choisy** [choisy/srtmVN#2]
SRTM data are not on disk.
Do you want to download them from the internet (108.0 MB)? y (default) / n
y
Error in utils::download.file(url, paste0(destdir, "/", file)) :
  scheme not supported in URL 'www.dropbox.com/s/94e42dmq3y0li3y/srtm90.tif?raw=1

**Comment by choisy** [comment]
The problem seems to occur on Windows machines only. So far, works OK on Mac and linux machines.

**Comment by LucieContamin** [comment]
Resolve in PR #3
